[build]
  functions = "netlify/functions"
  publish = "dist" 
  command = "npm run build" 

[functions]
  directory = ".netlify/functions" 

[context.production.environment]
  NODE_VERSION = "16"  


